#**~~ MAKEFILE ~~**#

CC = gcc 
DEBUG = $(FLAGS) -g -DDEBUG
FLAGS = -Wall -Wextra -Werror -pedantic  
HEAD = header.h



Example00 = strace_0 

ex_0.c -o ex_0

strace_0

strace_1

strace_2

strace_3


