CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

0-hreadelf: 0-hreadelf.c
	$(CC) $(CFLAGS) 0-hreadelf.c -o 0-hreadelf

1-hreadelf:  1-hreadelf.c
	$(CC) $(CFLAGS)  1-hreadelf.c -o 1-hreadelf
2-hreadelf: 2-hreadelf.c
	$(CC) $(CFLAGS) 2-hreadelf.c -o 2-hreadelf
